---
- name: Gather facts for the target machine
  hosts: testserver01
  gather_facts: yes # Ensures Ansible collects facts
  tasks:
    - name: Print all facts
      debug:
        var: ansible_facts

    - name: Show IP address
      debug:
        msg: "Target machine IP is {{ ansible_facts['ansible_default_ipv4']['address'] }}"
