---
- name: Gather facts for the target machine
  hosts: testserver01
  gather_facts: yes # Ensures Ansible collects facts
  tasks:
    - name: Print all facts
      debug:
        var: ansible_facts
